version: "3"

services:
  
  proxy:
    build: proxy
    ports:
      - 5000:80
    depends_on:
#      - frontend
      - api
    networks:
      - qac-net

  api:
    build: api
    networks: 
      - qac-net

networks:
  qac-net:
    driver: bridge
